### PR TITLE
feat: WAPI-1114 Add ETH account to claimed event

### PR DESCRIPTION
**Pull request by justraman**

### CODE REVIEW

**Comment by leonardocustodio** [comment]
Idk how the eth accounts are formatted but should we make it all lowercase? So if we ever got some with different case format they are threated the same?

**Comment by justraman** [comment]
> Idk how the eth accounts are formatted but should we make it all lowercase? So if we ever got some with different case format they are threated the same?

@leonardocustodio I think hex is always lowercase.

**Comment by leonardocustodio** [comment]
Not really, ethereum uses the case as a way of making checksum to the address: https://coincodex.com/article/2078/ethereum-address-checksum-explained/ I just don't know if in the Matrixchain we return with case sensitivity or not.
image

**Comment by leonardocustodio** [comment]
Ah but I see what you mean, you are not getting the raw address but converting bytes to hex. Yep in that case it may be all lowercase. Do you have a way to confirm?

**Comment by justraman** [comment]
I am 100% sure it's not a checksum address, the relayer is sending the lowered case. but to double sure I have replaced `.toString()` with `.toLowerCase()`

**Review by leonardocustodio — APPROVED** [review]

**Pull request merged**
